### PR TITLE
Add gsr_branch.py utility

### PR DESCRIPTION
**Pull request by nadavshemer**
Uses git-filter-branch to apply gsr on an entire branch's history. Also supports adding a gsr commit into an arbitrary point in history, using git-rebase to insert an empty commit and git-filter-branch to fill it in.

Since it depends entirely on gsr to be useful, I figure the gsr repo is a natural place for it.

### CODE REVIEW

**Comment by da-x** [comment]
Cool - just to complete this, please have setup.py include the plumbum dependency, and also have the this utility available when setup.py installs into the user's `$PATH`. Ok?

**Comment by da-x** [comment]
Should probably also move the exe into the 'bin' dir, to be consistent.

**Comment by da-x** [comment]
And make sure that it picks the correct GSR executable (the one that was installed along with it). Sorry for the 'finishing nitpicking'... :)

**Comment by nadavshemer** [comment]
Sounds simple enough. It looks like this:

diff --git a/gsr_branch.py b/bin/gsr_branch.py
similarity index 100%
rename from gsr_branch.py
rename to bin/gsr_branch.py
diff --git a/setup.py b/setup.py
index 1d2066b..386f9f6 100755
--- a/setup.py
+++ b/setup.py
@@ -8,7 +8,7 @@ setup(
     author='Dan Aloni',
     author_email='alonid@gmail.com',
     packages=['gitsearchreplace', 'bin'],
-    scripts=['bin/git-search-replace.py'],
+    scripts=['bin/git-search-replace.py', 'bin/gsr_branch.py'],
     url='https://github.com/da-x/git-search-replace',
     license='LICENSE.txt',
     description='a utility on top of git for project-wide '
@@ -19,4 +19,5 @@ setup(
         'Programming Language :: Python :: 2.7',
         'License :: OSI Approved :: BSD License',
     ],
+    requires=['plumbum']
 )

**Comment by nadavshemer** [comment]
I'm not sure I follow - the default 'gsr_cmd' value?
I want to add a 'build' phase?
Or you mean using the equivalent of "${BASH_SOURCE[0]}"?

**Comment by da-x** [comment]
Looks good - please rebase for merging.

**Pull request merged**
